name: Push

on:
  push:
    branches:
      - master

jobs:
  main:
    name: Build & test & publish
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build lib
        run: npm run build:lib
      - name: Build lib again
        run: npm run build:lib
      - name: Publish lib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPMTOKEN }}
        run: npm run release
